name: DevOps Managed Build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      application-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          echo "Building ${{ inputs.application-name }}"
          echo "Environment: ${{ inputs.environment }}"
